# Copyright (c) 2009 bivio Software, Inc.  All Rights Reserved.
# $Id$
package Freiker::Model::AcceptTermsForm;
use strict;
use Bivio::Base 'Biz.FormModel';

our($VERSION) = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);
my($_RT) = b_use('Model.RowTag');
b_use('Agent.Task')->register(__PACKAGE__);

sub execute_ok {
    my($self) = @_;
    $self->new_other('RowTag')->replace_value(
	$self->req('auth_user_id'), 'NEED_ACCEPT_TERMS');
    return;
}

sub handle_pre_execute_task {
    my($self, $task, $req) = @_;
    my($tid) = $task->get('id')->get_name;
    return
	unless $tid ne 'USER_ACCEPT_TERMS_FORM'
	and $tid =~ qr{^(?:FAMILY|CLUB|ADM|GREEN|USER)_}
	and my $uid = $req->get('auth_user_id');
    return {
	# Must be a client_redirect, because no ability to insert hidden
	# fields in form generated by Wiki
	method => 'client_redirect',
	task_id => 'USER_ACCEPT_TERMS_FORM',
    } if $_RT->new($req)->get_value($uid, 'NEED_ACCEPT_TERMS');
    return;
}

sub internal_initialize {
    my($self) = @_;
    return $self->merge_initialize_info($self->SUPER::internal_initialize, {
        version => 1,
	visible => [
	    {
		name => $self->OK_BUTTON_NAME,
		type => 'OKButton',
		constraint => 'NONE',
                form_name => 'accept',
	    },
	],
    });
}

1;
