# Copyright (c) 2013 bivio Software, Inc.  All Rights Reserved.
# $Id$
package Freiker::Facade::FR;
use strict;
use Bivio::Base 'Facade.Freiker';
b_use('IO.ClassLoaderAUTOLOAD');

our($VERSION) = sprintf('%d.%02d', q$Revision$ =~ /\d+/g);

__PACKAGE__->new({
    clone => 'Freiker',
    #TODO: turn on once ready for production
    is_production => 0,
    uri => 'fr.boltage',
    FormError => [
	['prose.detail_prefix' => q{; renseignement supplémentaire : }],
    ],
    Text => [
	['ok_button' => q{OK}],
	['cancel_button' => q{Annuler}],
	['MotionStatus.abstain_count' => q{S'abstenir}],
	['title.USER_ACCEPT_TERMS_FORM' => q{Acceptez les modalités de services et les politiques de confidentialité}],
	['title.DEFAULT_ERROR_REDIRECT_FORBIDDEN' => q{Accès refusé}],
	['title.FORBIDDEN' => q{Accès refusé}],
	['xlink.FORBIDDEN' => q{Accès refusé}],
	['GroupUserForm.RealmUser.role' => q{Niveau d'accès}],
	['UnapprovedApplicantForm.RealmUser.role' => q{Niveau d'accès}],
	['title.ADM_SUBSTITUTE_USER' => q{Agir en tant qu'utilisateur}],
	['title.SITE_ADMIN_SUBSTITUTE_USER' => q{Agir en tant qu'utilisateur}],
	['xlink.ADM_SUBSTITUTE_USER' => q{Agir en tant qu'utilisateur}],
	['xlink.substitute_user' => q{Agir en tant qu'utilisateur}],
	['FORUM_CALENDAR_EVENT_FORM.create' => q{Ajouter}],
	['RealmUserAddform.ok_button' => q{Ajouter}],
	['list_action.FORUM_CALENDAR_EVENT_FORM.create' => q{Ajouter un évènement}],
	['task_menu.title.FORUM_CALENDAR_EVENT_FORM.create' => q{Ajouter un évènement}],
	['FORUM_ADM_FORUM_ADD' => q{Ajouter un forum}],
	['title.GROUP_USER_ADD_FORM' => q{Ajouter un membre}],
	['CLUB_MANUAL_RIDE_FORM' => q{Ajouter un trajet manquant}],
	['FAMILY_MANUAL_RIDE_FORM' => q{Ajouter un trajet manquant}],
	['xhtml.title.CLUB_MANUAL_RIDE_FORM' => q{Ajouter un trajet manquant pour String([qw(Model.FreikerRideList ->get_display_name)]);}],
	['xhtml.title.FAMILY_MANUAL_RIDE_FORM' => q{Ajouter un trajet manquant pour String([qw(Model.FreikerRideList ->get_display_name)]);}],
	['CLUB_MANUAL_RIDE_LIST_FORM' => q{Ajouter des trajets manquants}],
	['FAMILY_MANUAL_RIDE_LIST_FORM' => q{Ajouter des trajets manquants}],
	['task_menu.title.CLUB_MANUAL_RIDE_LIST_FORM' => q{Ajouter des trajets manquants}],
	['task_menu.title.FAMILY_MANUAL_RIDE_LIST_FORM' => q{Ajouter des trajets manquants}],
	['title.CLUB_MANUAL_RIDE_LIST_FORM' => q{Ajouter des trajets manquants String([qw(Model.ManualRideListForm RealmOwner.display_name)]);}],
	['title.FAMILY_MANUAL_RIDE_LIST_FORM' => q{Ajouter des trajets manquants String([qw(Model.ManualRideListForm RealmOwner.display_name)]);}],
	['task_menu.title.FORUM_WIKI_EDIT' => q{Ajouter une nouvelle page}],
	['task_menu.title.MERCHANT_PRIZE' => q{Ajouter un prix}],
	['task_menu.title.FORUM_TUPLE_EDIT' => q{Ajouter une entrée}],
	['TupleUseForm.list_action.FORUM_TUPLE_EDIT' => q{Ajouter une entrée}],
	['TupleUseList.list_action.FORUM_TUPLE_EDIT' => q{Ajouter une entrée}],
	['ManualRideForm.ok_button' => q{Ajouter un trajet}],
	['ManualRideListForm.ok_button' => q{Ajouter des trajets}],
	['ManualRideListForm.use_type_for_all' => q{MÃªme moyen de transport pour tous les trajets}],
	['GroupUserList.privileges_name.ADMINISTRATOR' => q{Administrateur}],
	['prose.SiteAdminDropDown_label' => q{Administrateur}],
	['RoleSelectList.display_name.ADMINISTRATOR' => q{Administrateur}],
	['task_menu.title.SiteAdminDropDown_label' => q{Administrateur}],
	['ForumUserList.administrator' => q{Administrateur?}],
	['AcceptanceTestList.age' => q{Âge}],
	['title.ADM_PRIZE_COUPON_LIST' => q{Tous les prix remis}],
	['title.ADM_PRIZE_LIST' => q{Tous les prix}],
	['FreikerListQueryForm.fr_all' => q{Toutes les écoles}],
	['task_menu.title.ADM_RIDE_SUMMARY_LIST' => q{Tous les sommaires de trajets}],
	['title.SITE_ADMIN_USER_LIST' => q{Tous les utilisateurs}],
	['xlink.all_users' => q{Tous les utilisateurs}],
	['FreikerListQueryForm.fr_year' => q{Toutes les années}],
	['prose.LOGIN' => q{Déjà inscrit? Link('Cliquer ici pour vous connecter.', {task_id => 'LOGIN', no_context => 1});}],
	['acknowledgement.GENERAL_USER_PASSWORD_QUERY' => q{Un courriel a été envoyé à 
String([qw(Model.UserPasswordQueryForm Email.email)]);.
Vous trouverez dans le courriel un lien qui vous redirigera vers le site
afin de réinitialiser votre mot de passe.}],
	['task_menu.title.FORUM_CRM_FORM.reply_all' => q{Réponse}],
	['CRMQueryForm.b_owner_name' => q{Tous les propriétaires}],
	['CRMQueryForm.b_status' => q{Tous les statuts}],
	['MonthList.Apr' => q{Avr}],
	['prose.MERCHANT_REGISTER' => q{Êtes-vous un commerçant? vs_link('Cliquez ici pour inscrire votre entreprise.', 'MERCHANT_REGISTER');}],
	['RealmMailDeleteForm.prose.prologue' => q{Voulez-vous vraiment effacer le message SPAN_bold(String([qw(Model.RealmMailDeleteForm realm_mail subject)])); de SPAN_bold(String([qw(Model.RealmMailDeleteForm realm_mail from_email)]));?}],
	['RealmFileDeletePermanentlyForm.prose.prologue' => q{Voulez-vous vraiment effacer le message SPAN_bold(String([qw(->req path_info)])); pour toujours?}],
	['EmailVerifyForceForm.prose.prologue' => q{Êtes-vous certain de vouloir forcer la vérification de l'adresse courriel de  SPAN_bold(String([qw(Model.EmailVerifyForceForm display_name)])); (SPAN_bold(String([qw(Model.EmailVerifyForceForm email)]));)?}],
	['CalendarEventDeleteForm.prose.prologue' => q{Êtes-vous certain de vouloir effacer SPAN_bold(String([qw(Model.CalendarEventDeleteForm RealmOwner.display_name)])); du calendier?}],
	['RealmFileRestoreForm.prose.prologue' => q{Êtes-vous certain de vouloir restaurer SPAN_bold(String([qw(->req path_info)]));?}],
	['RealmFileRevertForm.prose.prologue' => q{Voulez-vous vraiment rétablir le fichier SPAN_bold(String([qw(Model.RealmFileRevertForm realm_file path)])); à la version SPAN_bold(String([qw(Model.RealmFileRevertForm new_version)]));?}],
	['attachment1' => q{Attacher}],
	['attachment2' => q{Attacher}],
	['attachment3' => q{Attacher}],
	['MonthList.Aug' => q{Août}],
	['MailThreadRootList.RealmMail.from_email' => q{Auteur}],
	['PrizeReceipt.receipt_code' => q{Code d'autorisation}],
	['task_menu.title.CLUB_PRIZE_LIST' => q{Récompense offerte}],
	['paged_detail.prev' => q{Retour}],
	['paged_list.prev' => q{Retour}],
	['paged_detail.list' => q{Retour à la liste}],
	['paged_list.list' => q{Retour à la liste}],
	['task_menu.title.TupleHistoryList.FORUM_TUPLE_LIST' => q{Retour à la liste}],
	['xlink.back_to_top' => q{Retour en haut}],
	['User.birth_date' => q{Date de naissance}],
	['feature_blog' => q{Blogue}],
	['title.FORUM_BLOG_LIST' => q{Blogue}],
	['title.FORUM_BLOG_RSS' => q{Blogue}],
	['title.FORUM_PUBLIC_BLOG_LIST' => q{Blogue}],
	['title.FORUM_PUBLIC_BLOG_RSS' => q{Blogue}],
	['title.FORUM_BLOG_DETAIL' => q{Détail du blogue}],
	['title.FORUM_PUBLIC_BLOG_DETAIL' => q{Détail du blogue}],
	['HelpWiki.title.DEFAULT_ERROR_REDIRECT_MISSING_COOKIES' => q{Cookies manquant dans le navigateur}],
	['task_menu.title.DEFAULT_ERROR_REDIRECT_MISSING_COOKIES' => q{Cookies manquant dans le navigateur}],
	['MerchantInfoForm.RealmOwner.display_name' => q{Nom de l'entreprise}],
	['MerchantInfoForm.Website.url' => q{Site web de l'entreprise}],
	['CalendarEventList.paged_detail.list' => q{Calendrier}],
	['CalendarEventList.paged_list.list' => q{Calendrier}],
	['CalendarEventMonthList.paged_detail.list' => q{Calendrier}],
	['CalendarEventMonthList.paged_list.list' => q{Calendrier}],
	['feature_calendar' => q{Calendrier}],
	['title.FORUM_CALENDAR' => q{Calendrier}],
	['title.FORUM_CALENDAR_EVENT_LIST_RSS' => q{Calendrier}],
	['xlink.FORUM_CALENDAR' => q{Calendrier}],
	['xlink.FORUM_CALENDAR_EVENT_LIST_RSS' => q{Calendrier}],
	['AdmSummaryBySchoolList.calories' => q{Calories brûlées}],
	['ClubFreikerClassList.calories' => q{Calories brûlées}],
	['ClubFreikerList.calories' => q{Calories brûlées}],
	['ClubSummaryByClassList.calories' => q{Calories brûlées}],
	['FreikerList.calories' => q{Calories brûlées}],
	['title.FORUM_FILE_CHANGE' => q{Modifier}],
	['title.USER_PASSWORD' => q{Modifier le mot de passe}],
	['RealmFileList.RealmFile.modified_date_time' => q{Modifié}],
	['RealmFileTreeList.RealmFile.modified_date_time' => q{Modifié}],
	['RealmFolderFileList.RealmFile.modified_date_time' => q{Modifié}],
	['title.USER_EMAIL_VERIFY_SENT' => q{Vérifier vos courriels}],
	['xlink.USER_CREATE_DONE' => q{Vérifier vos courriels}],
	['title.GENERAL_USER_PASSWORD_QUERY' => q{Vérifier vos courriels}],
	['title.USER_CREATE_DONE' => q{Vérifier vos courriels}],
	['RealmFileVersionsList.RealmFile.modified_date_time' => q{Enregistré}],
	['RealmFileVersionsListForm.RealmFile.modified_date_time' => q{Enregistré}],
	['task_menu.title.FAMILY_PRIZE_SELECT' => q{Choisir un prix}],
	['title.GREEN_GEAR_FORM' => q{Choisir le gagnant de la semaine}],
	['city' => q{Ville}],
	['AdmSummaryBySchoolList.class_display_name' => q{Classe}],
	['ClubFreikerClassList.class_display_name' => q{Classe}],
	['ClubFreikerList.class_display_name' => q{Classe}],
	['ClubSummaryByClassList.class_display_name' => q{Classe}],
	['ClubSummaryByClassList.realm_display_name' => q{Classe}],
	['FreikerList.class_display_name' => q{Classe}],
	['school_class_id' => q{Classe}],
	['SchoolClassList.display_name' => q{Classe}],
	['TupleSlotTypeListForm.TupleSlotType.type_class' => q{Classe}],
	['ClubFreikerClassList.school_class_id' => q{Numéro d'identification de la classe}],
	['ClubFreikerList.school_class_id' => q{Numéro d'identification de la classe}],
	['FreikerList.school_class_id' => q{Numéro d'identification de la classe}],
	['acknowledgement.CLUB_FREIKER_CLASS_LIST_FORM' => q{Classes mises à jour}],
	['DBAccessModelForm.clear_form_button' => q{Vider le formulaire}],
	['CRMActionList.label.closed' => q{Fermer}],
	['prose.help_wiki_close' => q{Fermer}],
	['MotionComment.comment' => q{Commentaire}],
	['MotionCommentDetail.comment' => q{Commentaire}],
	['MotionVote.comment' => q{Commentaire}],
	['title.FORUM_MOTION_COMMENT' => q{Commentaire}],
	['TupleHistoryList.comment' => q{Commentaire}],
	['TupleList.comment' => q{Commentaire}],
	['TupleSlotListForm.comment' => q{Commentaire}],
	['FileChangeForm.comment' => q{Commentaires}],
	['MotionStatus.comment_list' => q{Commentaires}],
	['RealmFileLock.comment' => q{Commentaires}],
	['RealmFileVersionsList.compare' => q{Comparer}],
	['RealmFileVersionsList.ok_button' => q{Comparer}],
	['RealmFileVersionsListForm.compare' => q{Comparer}],
	['RealmFileVersionsListForm.ok_button' => q{Comparer}],
	['title.CLUB_FREIKER_PRIZE_CONFIRM' => q{Confirmer le choix du prix}],
	['title.FAMILY_PRIZE_CONFIRM' => q{Confirmer votre choix de prix}],
	['title.FAMILY_PRIZE_SELECT' => q{Félicitations! Choisissez un prix! Vous avez String([qw(Model.PrizeSelectList ->get_prize_credit)]); crédits.}],
	['title.GENERAL_CONTACT' => q{Contacter}],
	['xlink.GENERAL_CONTACT' => q{Contacter}],
	['FORUM_CALENDAR_EVENT_FORM.copy' => q{Copier}],
	['prose.Base.xhtml_copyright' => q{Droit d'auteur &copy; vs_now_as_year(); vs_text_as_prose('site_copyright');<br />
Tous droits réservés.<br />
vs_text_as_prose('xhtml_copyright_qualifier');}],
	['prose.xhtml_copyright' => q{Droit d'auteur &copy; vs_now_as_year(); vs_text_as_prose('site_copyright');<br />
Tous droits réservés.<br />
vs_text_as_prose('xhtml_copyright_qualifier');}],
	['country' => q{Pays}],
	['Address.country' => q{Code du pays}],
	['FreikerImportForm.error.country_null' => q{Un pays doit être spécifié pour le premier enfant}],
	['PrizeCoupon.coupon_code' => q{Numéro d'identification du coupon}],
	['PrizeReceipt.coupon_code' => q{Numéro d'identification du coupon}],
	['DBAccessModelForm.create_button' => q{Créer}],
	['prize_credit' => q{Crédits}],
	['FreikerCodeImportForm.source' => q{Fichier CSV}],
	['FreikerImportForm.source' => q{Fichier CSV}],
	['old_password' => q{Mot de passe actuel}],
	['FreikerListQueryForm.fr_current' => q{Élèves actuels seulement}],
	['ManualRideForm.Ride.ride_date' => q{Date manquante}],
	['ClubRideFillForm.Ride.ride_date' => q{Date sans trajets}],
	['AllClubSummaryList.days_1' => q{Jour}],
	['MonthList.Dec' => q{Déc}],
	['TupleSlotTypeList.TupleSlotType.default_value' => q{Valeur par défaut}],
	['TupleSlotTypeListForm.TupleSlotType.default_value' => q{Valeur par défaut}],
	['CalendarEventDeleteForm.ok_button' => q{Effacer}],
	['DBAccessModelForm.delete_button' => q{Effacer}],
	['list_action.FORUM_CALENDAR_EVENT_DELETE' => q{Effacer}],
	['RealmMailDeleteForm.ok_button' => q{Effacer}],
	['task_menu.title.FORUM_CALENDAR_EVENT_DELETE' => q{Effacer}],
	['title.FORUM_CALENDAR_EVENT_DELETE' => q{Supprimer l'évènement}],
	['xlink.FORUM_CALENDAR_EVENT_DELETE' => q{Supprimer l'évènement}],
	['title.FORUM_FILE_DELETE_PERMANENTLY_FORM' => q{Effacer de façon permanente le fichier}],
	['title.GROUP_MAIL_DELETE_FORM' => q{Effacer le message}],
	['RealmFileDeletePermanentlyForm.ok_button' => q{Effacer de façon permanente}],
	['RealmFileList.list_action.FORUM_FILE_DELETE_PERMANENTLY_FORM' => q{Effacer de façon permanente}],
	['RealmFileTreeList.list_action.FORUM_FILE_DELETE_PERMANENTLY_FORM' => q{Effacer de façon permanente}],
	['RealmFolderFileList.list_action.FORUM_FILE_DELETE_PERMANENTLY_FORM' => q{Effacer de façon permanente}],
	['ClubPrizeConfirmForm.ok_button' => q{Remettre le prix}],
	['title.CLUB_FREIKER_SELECT' => q{Remettre le prix}],
	['AdmPrizeCouponList.PrizeCoupon.creation_date_time' => q{Remis}],
	['ClubPrizeCouponList.PrizeCoupon.creation_date_time' => q{Remis}],
	['title.CLUB_PRIZE_COUPON_LIST' => q{Prix remis}],
	['MobileToggler.desktop' => q{Bureau}],
	['prose.MailPartList.forward' => q{DIV_forward(Join([DIV_header('---------- Message transmis ----------'), MailHeader()]));}],
	['CRMForm.board_only' => q{Ne pas envoyer le message à vs_ui_forum(); vs_ui_members();}],
	['MailForm.board_only' => q{Ne pas envoyer le message à vs_ui_forum(); vs_ui_members();}],
	['task_menu.title.PAYPAL_FORM' => q{Faire un don}],
	['PayPalForm.ok_button' => q{Faire un don de façon sécuritaire via PayPal}],
	['task_menu.title.MERCHANT_PRIZE_LIST' => q{Prix qui était un don}],
	['title.MERCHANT_PRIZE_LIST' => q{Prix qui était un don}],
	['prose.help_wiki_edit' => q{Réviser}],
	['CLUB_FREIKER_EDIT' => q{Réviser les renseignements}],
	['FAMILY_FREIKER_EDIT' => q{Réviser les renseignements}],
	['title.FORUM_TUPLE_EDIT' => q{Edit String([qw(Model.TupleUseList TupleUse.label)]); entrée}],
	['FORUM_BLOG_EDIT' => q{Réviser cette entrée}],
	['task_menu.title.FORUM_WIKI_EDIT_PAGE' => q{Réviser cette page}],
	['GroupUserList.privileges_name.FILE_WRITER' => q{Rédacteur}],
	['RoleSelectList.display_name.FILE_WRITER' => q{Rédacteur}],
	['Email.email' => q{Courriel}],
	['parent_email' => q{Courriel}],
	['TaskLog.Email.email' => q{Courriel}],
	['acknowledgement.USER_EMAIL_VERIFY_FORCE_FORM' => q{Adresse courriel vérifiée.}],
	['CalendarEvent.dtend' => q{Fin}],
	['dtend_tz' => q{Fin}],
	['dtend_with_tz' => q{Fin}],
	['Motion.end_date_time' => q{Fin}],
	['MotionForm.end_date_string' => q{Fin}],
	['CalendarEventForm.end_date' => q{Date de fin}],
	['CalendarEventForm.end_time' => q{Heure de fin}],
	['MotionStatus.end_date_time' => q{Heure de fin}],
	['title.FORUM_CALENDAR_EVENT_DETAIL' => q{Évènement}],
	['xlink.FORUM_CALENDAR_EVENT_DETAIL' => q{Évènement}],
	['ClubRegisterForm.Website.url.desc' => q{Exemple: http://schools.bvsd.org/crestview/index.html}],
	['title.FORUM_EDIT_FORM' => q{Caractéristiques}],
	['title.REALM_FEATURE_FORM' => q{Caractéristiques}],
	['MonthList.Feb' => q{Fév}],
	['TupleDefListForm.TupleSlotDef.label' => q{Champ}],
	['TupleSlotDefList.TupleSlotDef.label' => q{Champ}],
	['UserSettingsListForm.RealmOwner.name.desc' => q{Champ visible seulement par les administrateurs du système.}],
	['UserSubscriptionList.RealmOwner.name.desc' => q{Champ visible seulement par les administrateurs du système.}],
	['feature_file' => q{Fichier}],
	['MotionStatus.file' => q{Fichier}],
	['title.FORUM_FILE' => q{Fichier}],
	['acknowledgement.FORUM_FILE_DELETE_PERMANENTLY_FORM' => q{Le fichier a été supprimé.}],
	['title.FORUM_FILE_VERSIONS_LIST' => q{Détails du fichier}],
	['acknowledgement.FORUM_FILE_RESTORE_FORM' => q{Le fichier a été restauré.}],
	['acknowledgement.FORUM_FILE_REVERT_FORM' => q{Le fichier a été rétabli.}],
	['FileChangeForm.file' => q{Le fichier a été téléchargé}],
	['AdmFreikometerList.list_action.FORUM_FILE_TREE_LIST' => q{Fichiers}],
	['title.FORUM_FILE_MANAGER' => q{Fichiers}],
	['title.FORUM_FILE_TREE_LIST' => q{Fichiers}],
	['title.forum_wiki_data' => q{Fichiers}],
	['title.MERCHANT_FILE' => q{Fichiers}],
	['title.ROBOT_FILE_LIST' => q{Fichiers}],
	['RemoteCopyList.to_delete' => q{Fichier à effacer:}],
	['RemoteCopyListForm.to_delete' => q{Fichier à effacer:}],
	['RemoteCopyList.to_update' => q{Fichiers à remplacer:}],
	['RemoteCopyListForm.to_update' => q{Fichiers à remplacer:}],
	['UserSettingsListForm.separator.password' => q{Compléter pour modifier votre mot de passe; sinon, laisser vide}],
	['UserSubscriptionList.separator.password' => q{Compléter pour modifier votre mot de passe; sinon, laisser vide}],
	['title.CLUB_RIDE_FILL_FORM' => q{Compléter les trajets}],
	['acknowledgement.CLUB_RIDE_FILL_FORM' => q{Compléter les trajets manquants lorsque le ZAP ne fonctionnait pas.}],
	['clear_on_focus_hint.GROUP_USER_LIST' => q{Filtre nom ou @courriel}],
	['clear_on_focus_hint.GROUP_TASK_LOG' => q{Filtre nom, >date, @courriel, /lien, ou x.y.z.}],
	['clear_on_focus_hint.GROUP_TASK_LOG_CSV' => q{Filtre nom, >date, @courriel, /lien, ou x.y.z.}],
	['clear_on_focus_hint.SITE_ADMIN_TASK_LOG' => q{Filtre nom, >date, @courriel, /lien, ou x.y.z.}],
	['clear_on_focus_hint.SITE_ADMIN_TASK_LOG_CSV' => q{Filtre nom, >date, @courriel, /lien, ou x.y.z.}],
	['FreikerCodeForm.User.first_name' => q{Premier}],
	['FreikerForm.User.first_name' => q{Premier}],
	['GreenGear.begin_date' => q{Premier jour}],
	['first_name' => q{Prénom}],
	['MailThreadRootList.RealmFile.modified_date_time' => q{Première entrée}],
	['Address.zip.desc' => q{Pour les rÃ©sidants des Ã‰tats-Unis, veuillez utiliser un code postal de 9 chiffre (Zip+4). Link('Regardez sur le site de USPS', 'http://zip4.usps.com/zip4/welcome.jsp', {link_target => '_blank'});.  Les autres utilisateurs doivent entrer leur code postal complet, excluant le prÃ©fixe du code du pays.}],
	['ActionError.wiki_name.FORBIDDEN' => q{Erreur - Accès non authorisé}],
	['EmailVerifyForceForm.ok_button' => q{Forcer la vérification}],
	['title.USER_EMAIL_VERIFY_FORCE_FORM' => q{Forcer la vérification de l'adresse courriel}],
	['xlink.GENERAL_USER_PASSWORD_QUERY' => q{Mot de passe oublié?}],
	['prose.GENERAL_USER_PASSWORD_QUERY' => q{Vous avez oublié votre mot de passe? Link('Cliquez ici pour le réinitialiser.', 'GENERAL_USER_PASSWORD_QUERY');}],
	['GroupUserList.privileges_name.WITHDRAWN' => q{Ancien membre}],
	['RoleSelectList.display_name.WITHDRAWN' => q{Ancien membre}],
	['CalendarEventWeekList.Friday' => q{Vendredi}],
	['EmailAliasList.EmailAlias.incoming' => q{Du Courriel}],
	['prose.MailHeader.from' => q{De:}],
	['RealmUserAddform.RealmOwner.display_name' => q{Nom complet}],
	['FreikerCodeForm.User.gender' => q{Sexe}],
	['FreikerForm.User.gender' => q{Sexe}],
	['User.gender' => q{Sexe}],
	['ClubManualRideForm.ok_button' => q{Donner les trajets}],
	['title.CLUB_FREIKER_MANUAL_RIDE_FORM' => q{Donner les trajets}],
	['xhtml.title.CLUB_FREIKER_MANUAL_RIDE_FORM' => q{Donner les trajets à String([qw(Model.FreikerRideList ->get_display_name)]);}],
	['xlink.page_error_referer' => q{Retourner à la page précédente, et essayer autre chose.}],
	['xlink.page_error_user' => q{Retourner à la page personnelle}],
	['xlink.page_error_visitor' => q{Aller à la page d'accueil.}],
	['ClubFreikerClassList.has_graduated' => q{Diplômé}],
	['ClubFreikerList.has_graduated' => q{Diplômé}],
	['FreikerList.has_graduated' => q{Diplômé}],
	['GroupUserList.privileges_name.GUEST' => q{Invité}],
	['RoleSelectList.display_name.GUEST' => q{Invité}],
	['FreikerCodeForm.has_graduated' => q{a été diplômé}],
	['FreikerForm.has_graduated' => q{a été diplômé}],
	['FreikerListQueryForm.fr_trips' => q{a des trajets}],
	['HelpWiki.header' => q{Aide}],
	['prose.help_wiki_header' => q{Aide}],
	['prose.help_wiki_open' => q{Aide}],
	['prose.help_wiki_page' => q{Aide}],
	['title.HELP' => q{Aide}],
	['title.HELP_NOT_FOUND' => q{Page d'aide introuvable}],
	['list_action.FORUM_TUPLE_HISTORY' => q{Historique}],
	['task_menu.title.SITE_WIKI_VIEW' => q{Accueil}],
	['title.SITE_ROOT' => q{Accueil}],
	['WikiView.start_page' => q{Accueil}],
	['xlink.SITE_ROOT' => q{Accueil}],
	['AcceptanceTestTransactionList.http_status' => q{état HTTP}],
	['UserRegisterForm.ok_button' => q{J'accepte. Créer mon compte.}],
	['GreenGear.must_be_unique' => q{Si possible, exclure les gagnants précédants.}],
	['ClubFreikerClassListForm.prose.prologue' => q{If(['!', 'auth_realm', 'type', '->eq_user'], Link("Cliquer ici pour réviser la liste des classes de l'école.", 'CLUB_SCHOOL_CLASS_LIST_FORM'));}],
	['FreikerForm.prose.prologue' => q{If(['!', 'form_model', 'in_parent_realm'], Link("Cliquer ici pour réviser la liste des classes de l'école.", 'CLUB_SCHOOL_CLASS_LIST_FORM'));}],
	['title.FORUM_MAIL_FORM' => q{If(['->has_keys', 'Model.RealmMailList'], 'Répondre', 'Nouveau sujet');}],
	['FreikerCodeForm.prose.prologue' => q{If(['Model.FreikerCodeForm', 'in_parent_realm'], Prose(q{Inscrivez le nouveau code Boltage de l'étiquette Zap se trouvant sur le sac à dos de votre enfant. Si l'étiquette est manquante, ou si vous en avez besoin d'une nouvelle pour un nouveau sac à dos, vs_wheel_contact<(>)<;>.}), vs_text_as_prose('FreikerForm.prose.prologue'));}],
	['FreikerCodeForm.ok_button' => q{If([qw(->ureq Model.FreikerRideList)], 'Ajouter le numéro de l'étiquette Zap', 'Inscrire un enfant');}],
	['RemoteCopyList.ok_button' => q{If([qw(Model.RemoteCopyListForm prepare_ok)], 'Copier', 'Préparer');}],
	['RemoteCopyListForm.ok_button' => q{If([qw(Model.RemoteCopyListForm prepare_ok)], 'Copier', 'Préparer');}],
	['title.MERCHANT_PRIZE' => q{If(['Type.FormMode', '->eq_edit'], 'Mettre à jour les renseignements des prix', 'Faire le don d'un prix');}],
	['FreikerCodeImportForm.ok_button' => q{Importer}],
	['FreikerImportForm.ok_button' => q{Importer les enfants}],
	['title.CLUB_FREIKER_IMPORT_FORM' => q{Importer les enfants}],
	['CalendarEventForm.start_time.desc' => q{Dans le fuseau horaire sélectionné}],
	['title.DEFAULT_ERROR_REDIRECT_UPDATE_COLLISION' => q{Données invalides}],
	['prose.UserAuth.missing_cookies.body' => q{Join([
    P("Il semble que votre navigateur n'accepte pas les cookies, ou que les cookies ont été désactivés. Les cookies sont requis pour vous inscrire."),
    H3('Activer les cookies dans votre navigateur'),
    P(q{Cette application requiert l'utilisation des cookies. Par défaut, les cookies sont activés dans votre navigateur. Si vous avez été redirigé vers cette page par notre logiciel, cela veut dire que quelqu'un a désactivé les cookies dans votre navigateur. Les instructions qui suivent sont à titre indicatif seulement. Veuillez consulter la rubrique d'aide de votre navigateur pour une description complète. Veuillez consulter la page ci-dessous jusqu'à ce que vous trouvez votre navigateur. Nous sommes désolés si votre navigateur ne fait pas parti de la liste.}),
    map((
	H4(shift(@$_)),
	OL(Join([map(LI($_), @$_)])),
    ), [
	'Internet Explorer 6.0',
'Cliquez sur le menu Outils (dans le haut de la fenêtre)',
'Sélectionnez Options Internet',
'Sélectionnez l'onglet Confidentialié',
'Faites glisser la barre verticale à Moyenne',
    ], [
'Versions plus anciennes d'Internet Explorer',
'Cliquez sur le menu Outils (dans le haut de la fenêtre)',
'Sélectionnez Options Internet',
'Sélectionnez l'onglet Confidentialité',
'Cliquez sur Internet dans Sélectionner la zone de contenu web',
'Plus bas, cliquez sur le bouton Personnalisé le niveau de sécurité',

	'Further down, press the Custom Level button',
	'Scroll down to the Cookies section in the Settings box',
	'Click on Enable for Allow cookies that are stored option',
	'Click on Enable for Allow per-session cookies option',
    ], [
	'Older AOL Versions',
	'Click on My AOL at the top of the AOL window',
	'Select Preferences from the menu',
	'Click on the WWW icon',
	'Click on Internet in the Select a Web content zone',
	'Further down, press the Custom Level button',
	'Scroll down to the Cookies section in the Settings box',
	'Click on Enable for Allow cookies that are stored option',
	'Click on Enable for Allow per-session cookies option',
    ], [
	'Netscape Communicator',
	'Click on the Edit menu (at the very top of your window)',
	'Select Preferences',
	'Click on Advanced in the Category box',
	'Click on Accept all cookies in the Cookies box',
    ]),
]);
}],
	['MonthList.Jul' => q{Juil}],
	['MonthList.Jun' => q{Juin}],
	['AdmPrizeCouponList.RealmOwner.display_name' => q{enfant}],
	['ClubFreikerClassList.display_name' => q{enfant}],
	['ClubFreikerClassList.User.first_name' => q{enfant}],
	['ClubFreikerList.display_name' => q{enfant}],
	['ClubFreikerList.User.first_name' => q{enfant}],
	['ClubPrizeCouponList.RealmOwner.display_name' => q{enfant}],
	['FreikerList.display_name' => q{enfant}],
	['FreikerList.User.first_name' => q{enfant}],
	['GreenGearList.RealmOwner.display_name' => q{enfant}],
	['GreenGear.must_be_registered' => q{L'enfant doit être inscrit afin d'être éligible au tirage.}],
	['prose.USER_CREATE' => q{Enfant non inscrit?  vs_link("Cliquez ici pour l'inscrire.", 'USER_CREATE');}],
	['task_menu.title.back_to_club' => q{Enfants}],
	['task_menu.title.CLUB_FREIKER_CLASS_LIST' => q{Enfants}],
	['task_menu.title.CLUB_FREIKER_LIST' => q{Enfants}],
	['title.CLUB_FREIKER_LIST' => q{Enfants}],
	['title.CLUB_FREIKER_CLASS_LIST' => q{Enfants dans String([qw(Model.ClubFreikerClassList ->get_class_display_name)]);}],
	['distance_kilometers' => q{kilomètres}],
	['kilometers' => q{kilomètres}],
	['FreikerCodeForm.kilometers' => q{Kilomètres jusqu'à l'école}],
	['FreikerForm.kilometers' => q{Kilomètres jusqu'à l'école}],
	['FreikerCodeForm.User.last_name' => q{Dernier}],
	['FreikerForm.User.last_name' => q{Dernier}],
	['GreenGear.end_date' => q{Dernier jour}],
	['last_name' => q{Nom de famille}],
	['MailThreadRootList.RealmFile_2.modified_date_time' => q{Dernière entrée}],
	['ManualRideListForm.prose.prologue' => q{Dernier trajet: If([qw(Model.ManualRideListForm last_ride)], Join([DateTime([qw(Model.ManualRideListForm last_ride ride_date)], 'DATE'), ' (', String([qw(Model.ManualRideListForm last_ride ride_type ->get_short_desc)]), ')']), 'None');}],
	['CRMThreadRootList.CRMThread.modified_date_time' => q{Dernière mise à jour}],
	['TupleList.Tuple.modified_date_time' => q{Dernière mise à jour}],
	['TupleSlotListForm.Tuple.modified_date_time' => q{Dernière mise à jour}],
	['Prize.modified_date_time' => q{Dernier mis à jour}],
	['AdmFreikometerList.modified_date_time' => q{Dernier téléchargement}],
	['email_verified_date_time' => q{Dernier vérifié}],
	['GroupUserList.display_name' => q{Nom de famille, Prénom}],
	['TaskLog.uri' => q{Lien}],
	['url' => q{Lien}],
	['UserSettingsListForm.prose.user_password' => q{Link('Cliquez ici pour changer votre mot de passe.', 'USER_PASSWORD');}],
	['UserSubscriptionList.prose.user_password' => q{Link('Cliquez ici pour changer votre mot de passe.', 'USER_PASSWORD');}],
	['acknowledgement.REMOTE_COPY_FORM' => q{Système local mis à jour.}],
	['ContextlessUserLoginForm.ok_button' => q{Ouverture de session}],
	['title.my_site_login' => q{Ouverture de session}],
	['title.user_logged_out' => q{Ouverture de session}],
	['UserLoginForm.ok_button' => q{Ouverture de session}],
	['xlink.LOGIN' => q{Ouverture de session}],
	['xlink.login_no_context' => q{Ouverture de session}],
	['xlink.my_site_login' => q{Ouverture de session}],
	['xlink.user_logged_out' => q{Ouverture de session}],
	['title.LOGOUT' => q{Fermeture de session}],
	['title.user_logged_in' => q{Fermeture de session}],
	['xlink.LOGOUT' => q{Fermeture de session}],
	['xlink.user_logged_in' => q{Fermeture de session}],
	['CalendarEventForm.end_date.desc' => q{m/j/aa, j.m.aa, aaaa/m/j, d-mon-aaaa, ou mmjjaa}],
	['CalendarEventForm.start_date.desc' => q{m/j/aa, j.m.aa, aaaa/m/j, d-mon-aaaa, ou mmjjaa}],
	['feature_mail' => q{Courriel}],
	['task_menu.title.FORUM_MAIL_THREAD_ROOT_LIST' => q{Courriel}],
	['title.FORUM_MAIL_THREAD_ROOT_LIST' => q{Courriel}],
	['MonthList.Mar' => q{Mars}],
	['MonthList.May' => q{Mai}],
	['GroupUserList.privileges_name.MEMBER' => q{Membre}],
	['RoleSelectList.display_name.MEMBER' => q{Membre}],
	['vs_ui.members' => q{Membres}],
	['RealmDropDown.merchant' => q{Commerçant}],
	['acknowledgement.GROUP_MAIL_DELETE_FORM' => q{Effacer le message}],
	['FreikerCodeForm.User.middle_name' => q{deuxième}],
	['FreikerForm.User.middle_name' => q{deuxième}],
	['middle_name' => q{Deuxième prénom}],
	['miles' => q{miles}],
	['FreikerCodeForm.miles' => q{Miles jusqu'à l'école}],
	['FreikerForm.miles' => q{Miles jusqu'à l'école}],
	['MobileToggler.mobile' => q{Cellulaire}],
	['Ride.ride_type' => q{Moyen de transport}],
	['FORUM_CALENDAR_EVENT_FORM.edit' => q{Modifier}],
	['list_action.FORUM_TUPLE_DEF_EDIT' => q{Modifier}],
	['list_action.FORUM_TUPLE_EDIT' => q{Modifier}],
	['list_action.FORUM_TUPLE_SLOT_TYPE_EDIT' => q{Modifier}],
	['list_action.FORUM_TUPLE_USE_EDIT' => q{Modifier}],
	['RealmFileList.list_action.FORUM_FILE_CHANGE' => q{Modifier}],
	['RealmFileTreeList.list_action.FORUM_FILE_CHANGE' => q{Modifier}],
	['RealmFolderFileList.list_action.FORUM_FILE_CHANGE' => q{Modifier}],
	['task_menu.title.TupleHistoryList.FORUM_TUPLE_EDIT' => q{Modifier l'entrée}],
	['CalendarEventWeekList.Monday' => q{Lundi}],
	['AllClubSummaryList.days_20' => q{mois}],
	['RealmFileList.more_files' => q{plus …}],
	['RealmFileTreeList.more_files' => q{plus …}],
	['RealmFolderFileList.more_files' => q{plus …}],
	['add_rows' => q{Insérer une ligne}],
	['AdmUserList.display_name' => q{Nom}],
	['DBAccessModelList.name' => q{Nom}],
	['FileChangeForm.name' => q{Nom}],
	['Motion.name' => q{Nom}],
	['MotionCommentDetail.name' => q{Nom}],
	['MotionCommentList.RealmOwner.display_name' => q{Nom}],
	['MotionStatus.name' => q{Nom}],
	['Prize.name' => q{Nom}],
	['RealmFileList.RealmFile.path' => q{Nom}],
	['RealmFileTreeList.RealmFile.path' => q{Nom}],
	['RealmFolderFileList.RealmFile.path' => q{Nom}],
	['TaskLogList.RealmOwner.display_name' => q{Nom}],
	['UnapprovedApplicantList.display_name' => q{Nom}],
	['CRMActionList.label.new' => q{Nouveau}],
	['FORUM_BLOG_CREATE' => q{Nouvel entrée pour le blogue}],
	['acknowledgement.CLUB_FREIKER_CODE_IMPORT' => q{Nouveaux codes importés avec succès.}],
	['RemoteCopyList.to_create' => q{Nouveaux fichiers à copier:}],
	['RemoteCopyListForm.to_create' => q{Nouveaux fichiers à copier:}],
	['FileChangeForm.rename_name' => q{Nouveau nom}],
	['FileChangeForm.folder_id' => q{Nouveau dossier parent}],
	['new_password' => q{Nouveau mot de passe}],
	['title.FORUM_MOTION_FORM' => q{Nouveau sondage}],
	['task_menu.title.FORUM_CRM_FORM' => q{Nouveau billet}],
	['task_menu.title.FORUM_MAIL_FORM' => q{Nouveau sujet}],
	['CLUB_FREIKER_CODE_ADD' => q{Nouvelle étiquette Zap}],
	['FAMILY_FREIKER_CODE_ADD' => q{Nouvelle étiquette Zap}],
	['paged_detail.next' => q{Suivant}],
	['paged_list.next' => q{Suivant}],
	['MotionStatus.no_count' => q{Non}],
	['GroupUserList.privileges_name.UNKNOWN' => q{Pas d'accès}],
	['RoleSelectList.display_name.UNKNOWN' => q{Pas d'accès}],
	['TupleList.empty_list_prose' => q{Aucune entrée dans la base de données a été ajoutée.}],
	['TupleSlotListForm.empty_list_prose' => q{Aucune entrée dans la base de données a été ajoutée.}],
	['BlogList.empty_list_prose' => q{Aucune entrée dans ce blogue}],
	['CalendarEventList.empty_list_prose' => q{Aucun évènement pendant cette période.}],
	['CalendarEventMonthList.empty_list_prose' => q{Aucun évènement pendant cette période.}],
	['RealmFileList.empty_list_prose' => q{Aucun fichier dans ce forum.}],
	['RealmFileTreeList.empty_list_prose' => q{Aucun fichier dans ce forum.}],
	['RealmFolderFileList.empty_list_prose' => q{Aucun fichier dans ce forum.}],
	['ClubFreikerClassList.empty_list_prose' => q{Aucun enfant pour le moment.}],
	['ClubFreikerList.empty_list_prose' => q{Aucun enfant pour le moment.}],
	['FreikerList.empty_list_prose' => q{Aucun enfant pour le moment.}],
	['MotionVoteList.empty_list_prose' => q{Aucune réponse pour le sondage.}],
	['MotionList.empty_list_prose' => q{Aucun sondage à afficher.}],
	['Image_alt.none' => q{aucun}],
	['DieCode.MODEL_NOT_FOUND' => q{Introuvable}],
	['title.DEFAULT_ERROR_REDIRECT_MODEL_NOT_FOUND' => q{Introuvable}],
	['title.DEFAULT_ERROR_REDIRECT_NOT_FOUND' => q{Introuvable}],
	['CalendarEventForm.recurrence.desc' => q{Note: les évènements récurrents ne peuvent être mis à jour en ce moment}],
	['ActionError.wiki_name.MODEL_NOT_FOUND' => q{Erreur - Page non trouvée}],
	['ActionError.wiki_name.NOT_FOUND' => q{Erreur - Page non trouvée}],
	['ClubManualRideForm.add_days' => q{Nombre de jours}],
	['ClubRegisterForm.club_size' => q{Nombre d'élèves}],
	['club_name' => q{Nom officiel}],
	['Address.country.desc' => q{Deux premières lettres officielles du pays (US, CA, MX, etc.)}],
	['AdmPrizeForm.ok_button' => q{Ok}],
	['MerchantPrizeForm.ok_button' => q{Ok}],
	['FreikerImportForm.error.none_kilometers_miles' => q{Choisir entre kilomètres et miles}],
	['ClubFreikerClassList.FreikerInfo.distance_kilometers' => q{Kilomètres aller-simple}],
	['ClubFreikerList.FreikerInfo.distance_kilometers' => q{Kilomètres aller-simple}],
	['FreikerList.FreikerInfo.distance_kilometers' => q{Kilomètres aller-simple}],
	['ClubFreikerClassList.miles' => q{Miles aller-simple}],
	['ClubFreikerList.miles' => q{Miles aller-simple}],
	['FreikerList.miles' => q{Miles aller-simple}],
	['FreikerCodeForm.kilometers.desc' => q{Distance aller-simple à partir de la maison jusqu'à l'école de l'enfant. Les enfants ayant plus d'une maison, calculer la distance pour la maison du code postal ci-dessus.}],
	['FreikerCodeForm.miles.desc' => q{Distance aller-simple à partir de la maison jusqu'à l'école de l'enfant. Les enfants ayant plus d'une maison, calculer la distance pour la maison du code postal ci-dessus.}],
	['FreikerForm.kilometers.desc' => q{Distance aller-simple à partir de la maison jusqu'à l'école de l'enfant. Les enfants ayant plus d'une maison, calculer la distance pour la maison du code postal ci-dessus.}],
	['FreikerForm.miles.desc' => q{Distance aller-simple à partir de la maison jusqu'à l'école de l'enfant. Les enfants ayant plus d'une maison, calculer la distance pour la maison du code postal ci-dessus.}],
	['SearchForm.b_realm_only' => q{Seulement dans String([qw(->req auth_realm owner display_name)]);}],
	['FreikerCodeForm.User.first_name.desc' => q{Seulement le prénom ou le nom de famille est requis.}],
	['FreikerForm.User.first_name.desc' => q{Seulement le prénom ou le nom de famille est requis.}],
	['FreikerImportForm.error.both_kilometers_miles' => q{Choisir seulement un entre kilomètres et miles}],
	['RealmUserAddform.RealmOwner.display_name.desc' => q{Seulement requis pour les nouveaux utilisateurs}],
	['Image_alt.bivio_power' => q{Exploité par bivio Software, Inc.}],
	['separator.optional_address' => q{Renseignements optionnels pour nous aider à vous contacter}],
	['separator.optional_statistics' => q{Renseignements optionnels utilisés à des fins statisques.}],
	['AcceptanceTestList.outcome' => q{résultat}],
	['UserRegisterForm.prose.prologue' => q{P('Afin de mieux vous servir, nous validons chacune des adresses courriels. Lorsque vous cliquez sur inscription, nous vous enverrons un lien qui vous demandera de choisir un mot de passe.');}],
	['UserRegisterForm.prose.epilogue' => q{P(vs_text_as_prose('LOGIN'));
P(Join([
    q{En cliquant sur "J'accepte" ci-dessous, vous acceptez les },
    Link('ModalitÃ©s de service', '/bp/Terms_of_Service'),
    ' et les ',
    Link('Politique de confidentialitÃ©', '/bp/Privacy_Policy'),
    '.',
]));
</p>
}],
	['UserPasswordQueryForm.prose.prologue' => q{P_prose("Veuillez entrer l'adresse courriel que vous avez utilisé pour vous inscrire et cliquez sur envoyer. Vous recevrez un courriel avec un lien pour réinitialiser votre mot de passe.");}],
	['task_menu.title.FORUM_WIKI_VERSIONS_LIST' => q{Historique de la page}],
	['AdmPrizeCouponList.family_display_name' => q{parent}],
	['ClubPrizeCouponList.family_display_name' => q{parent}],
	['parent_display_name' => q{parent}],
	['parent_display_name_sort' => q{parent}],
	['parent_first_name' => q{Prénom du parent}],
	['parent_last_name' => q{Nom de famille du parent}],
	['parent_zip' => q{Code postal du parent}],
	['password' => q{Mot de passe}],
	['xlink.USER_PASSWORD' => q{Mot de passe}],
	['title.GENERAL_USER_PASSWORD_QUERY_ACK' => q{Aide au mot de passe envoyé}],
	['xlink.GENERAL_USER_PASSWORD_QUERY_ACK' => q{Aide au mot de passe envoyé}],
	['task_menu.title.FAMILY_PRIZE_COUPON_LIST' => q{Derniers prix}],
	['title.FAMILY_PRIZE_COUPON_LIST' => q{Derniers prix}],
	['CRMActionList.label.pending_customer' => q{Client en attente}],
	['title.USER_SETTINGS_FORM' => q{Coordonnées et paramètres}],
	['xlink.USER_SETTINGS_FORM' => q{Renseignements personnels et paramètres}],
	['phone' => q{Téléphone}],
	['page3.title.GENERAL_CONTACT' => q{Veuillez nous contacter}],
	['xhtml.title.GENERAL_CONTACT' => q{Veuillez nous contacter}],
	['form_error_title' => q{Veuillez corriger les erreurs ci-dessous:}],
	['prose.UserAuth.password_query_mail.body' => q{Veuillez cliquer sur le lien suivant pour rÃ©initialiser votre mot de passe:

Join([['Model.UserPasswordQueryForm', 'uri']]);

Pour votre sÃ©curitÃ©, ce lien ne peut Ãªtre utilisÃ© qu'une seule fois
pour programmer votre mot de passe.

Veuillez rÃ©pondre Ã  ce courriel pour contacter le soutien Ã  la clientÃ¨le.
Merci,
Support vs_site_name();}],
	['acknowledgement.CLUB_FREIKER_PRIZE_CONFIRM' => q{Veuillez remettre les prix choisis à l'enfant.}],
	['page3.title.LOGIN' => q{Ouvrir une session}],
	['title.LOGIN' => q{Ouvrir une session}],
	['xhtml.title.LOGIN' => q{Ouvrir une session}],
	['page3.title.USER_CREATE' => q{Inscription}],
	['title.USER_CREATE' => q{Inscription}],
	['xhtml.title.USER_CREATE' => q{Inscription}],
	['acknowledgement.update_address' => q{Veuillez mettre à jour les renseignements ci-dessous. Nous devons nous assurer que les informations sont à jour.}],
	['feature_motion' => q{Sondage}],
	['title.FORUM_MOTION_COMMENT_LIST' => q{Commentaires du sondage}],
	['title.FORUM_MOTION_VOTE_LIST' => q{Résultats du sondage}],
	['title.FORUM_MOTION_STATUS' => q{Statut du sondage}],
	['title.FORUM_MOTION_LIST' => q{Sondages}],
	['Address.zip' => q{Code postal}],
	['AdmSummaryBySchoolList.co2_saved' => q{Livres de CO2 économisés}],
	['ClubFreikerClassList.co2_saved' => q{Livres de CO2 économisés}],
	['ClubFreikerList.co2_saved' => q{Livres de CO2 économisés}],
	['ClubSummaryByClassList.co2_saved' => q{Livres de CO2 économisés}],
	['FreikerList.co2_saved' => q{Livres de CO2 économisés}],
	['summary_headings.co2_saved' => q{Livres de CO2 économisés}],
	['AdmUserList.privileges' => q{Privilèges}],
	['GroupUserList.privileges' => q{Privilèges}],
	['UnapprovedApplicantList.privileges' => q{Privilèges}],
	['title.GROUP_USER_FORM' => q{Privilèges pour String(['->req', 'Model.GroupUserList', 'RealmOwner.display_name']);}],
	['HelpWiki.title.GROUP_USER_FORM' => q{Privilèges pour l'utilisateur}],
	['AdmPrizeCouponList.Prize.name' => q{Prix}],
	['ClubPrizeCouponList.Prize.name' => q{Prix}],
	['FAMILY_PRIZE_COUPON_LIST' => q{Prix}],
	['title.GROUP_BULLETIN_FORM' => q{Publier le bulletin}],
	['title.ALL_CLUB_SUMMARY_LIST' => q{Trajets en temps réel}],
	['UnapprovedApplicantForm.mail_recipient' => q{Recevoir le courriel envoyé au groupe (Inscrits)}],
	['GroupUserForm.mail_recipient' => q{Recevoir le courriel envoyé à vs_ui_forum(); (Inscrits)}],
	['TupleList.Tuple.tuple_num' => q{Entrée}],
	['TupleSlotListForm.Tuple.tuple_num' => q{#Entrée}],
	['list_action.FORUM_TUPLE_LIST' => q{Entrées}],
	['task_menu.title.FORUM_TUPLE_LIST' => q{Entrées}],
	['confirm_new_password' => q{Entrer à nouveau le nouveau mot de passe}],
	['confirm_password' => q{Entrer à nouveau le mot de passe}],
	['FreikerListQueryForm.ok_button' => q{Actualiser}],
	['vs_selector_form.ok_button' => q{Actualiser}],
	['title.user_just_visitor' => q{Inscrire}],
	['UserCreateForm.ok_button' => q{Inscrire}],
	['xlink.USER_CREATE' => q{Inscrire}],
	['xlink.user_create_no_context' => q{Inscrire}],
	['xlink.user_just_visitor' => q{Inscrire}],
	['title.CLUB_FREIKER_ADD' => q{Inscrire un enfant}],
	['task_menu.title.CLUB_FREIKER_ADD' => q{Inscrire un enfant}],
	['task_menu.title.FAMILY_FREIKER_ADD' => q{Inscrire un enfant}],
	['MerchantInfoForm.ok_button' => q{Inscrire un commerçant}],
	['task_menu.title.MERCHANT_REGISTER' => q{Inscrire un nouveau commerçant}],
	['task_menu.title.CLUB_REGISTER' => q{Inscrire une nouvelle école}],
	['ClubRegisterForm.ok_button' => q{Inscrire une école}],
	['FreikerCodeForm.no_freiker_code' => q{Inscrire sans un numéro d'étiquette Zap}],
	['FreikerForm.no_freiker_code' => q{Inscrire sans un numéro d'étiquette Zap}],
	['title.MERCHANT_REGISTER' => q{Inscrire votre entreprise}],
	['title.FAMILY_FREIKER_ADD' => q{Inscrire votre enfant}],
	['title.CLUB_REGISTER' => q{Inscrire votre école}],
	['FreikerListQueryForm.fr_registered' => q{Inscrit}],
	['GroupUserList.privileges_name.USER' => q{Utilisateur inscrit}],
	['RoleSelectList.display_name.USER' => q{Utilisateur inscrit}],
	['UnapprovedApplicantForm.mail_subject.default' => q{Inscription confirmé}],
	['GroupUserList.RealmOwner.creation_date_time' => q{Date d'inscription}],
	['UnapprovedApplicantList.RealmOwner.creation_date_time' => q{Date d'inscription}],
	['MailThreadRootList.reply_count' => q{Réponses}],
	['task_menu.title.FORUM_MAIL_FORM.reply_realm' => q{Répondre}],
	['task_menu.title.FORUM_MAIL_FORM.reply_all' => q{Répondre à tous}],
	['task_menu.title.FORUM_MAIL_FORM.reply_author' => q{Répondre à l'auteur}],
	['GroupUserList.privileges_name.UNAPPROVED_APPLICANT' => q{Accès requis}],
	['RoleSelectList.display_name.UNAPPROVED_APPLICANT' => q{Accès requis}],
	['Prize.ride_count' => q{Trajets requis}],
	['TupleDefListForm.TupleSlotDef.is_required' => q{Requis?}],
	['TupleSlotDefList.TupleSlotDef.is_required' => q{Requis?}],
	['RealmFileList.list_action.FORUM_FILE_RESTORE_FORM' => q{Restaurer}],
	['RealmFileRestoreForm.ok_button' => q{Restaurer}],
	['RealmFileTreeList.list_action.FORUM_FILE_RESTORE_FORM' => q{Restaurer}],
	['RealmFolderFileList.list_action.FORUM_FILE_RESTORE_FORM' => q{Restaurer}],
	['title.FORUM_FILE_RESTORE_FORM' => q{Restaurer le fichier}],
	['Prize.retail_price' => q{Prix de vente}],
	['AdmPrizeCouponList.list_action.CLUB_FREIKER_PRIZE_DELETE' => q{Retourner}],
	['ClubPrizeCouponList.list_action.CLUB_FREIKER_PRIZE_DELETE' => q{Retourner}],
	['ClubPrizeDeleteForm.ok_button' => q{Retourner le prix}],
	['title.CLUB_FREIKER_PRIZE_DELETE' => q{Retourner le prix pour String([qw(Model.ClubPrizeCouponList ->get_display_name)]);}],
	['RealmFileRevertForm.ok_button' => q{Rétablir}],
	['title.FORUM_FILE_REVERT_FORM' => q{Rétablir le fichier}],
	['RealmFileVersionsList.list_action.FORUM_FILE_REVERT_FORM' => q{Rétablir à la version}],
	['RealmFileVersionsListForm.list_action.FORUM_FILE_REVERT_FORM' => q{Rétablir à la version}],
	['RealmFileVersionsList.RealmFile.path' => q{Révision}],
	['RealmFileVersionsList.revision_number' => q{Révision}],
	['RealmFileVersionsListForm.RealmFile.path' => q{Révision}],
	['RealmFileVersionsListForm.revision_number' => q{Révision}],
	['CalendarEventWeekList.Saturday' => q{Samedi}],
	['TupleDefListForm.ok_button' => q{Sauvegarder}],
	['TupleSlotListForm.ok_button' => q{Sauvegarder}],
	['TupleSlotTypeListForm.ok_button' => q{Sauvegarder}],
	['TupleUseForm.ok_button' => q{Sauvegarder}],
	['WikiForm.ok_no_validate_button' => q{Sauvegarder}],
	['AdmSummaryBySchoolList.realm_display_name' => q{École}],
	['AllClubSummaryList.RealmOwner.display_name' => q{École}],
	['club_id' => q{École}],
	['RealmDropDown.club' => q{École}],
	['title.CLUB_PRIZE_LIST' => q{Prix de l'école}],
	['ClubRegisterForm.Website.url' => q{Site web de l'école}],
	['DBAccessModelForm.search_button' => q{Recherche}],
	['SearchForm.ok_button' => q{Recherche}],
	['title.GROUP_SEARCH_LIST' => q{Résultats de la recherche}],
	['title.SEARCH_LIST' => q{Résultats de la recherche}],
	['SchoolClassList.RealmOwner.display_name.select' => q{Sélectionner une classe}],
	['FAMILY_PRIZE_SELECT' => q{Sélectionner un prix}],
	['title.CLUB_FREIKER_PRIZE_SELECT' => q{Sélectionner un prix}],
	['xhtml.title.CLUB_FREIKER_PRIZE_SELECT' => q{Sélectionner un prix pour String([qw(Model.ClubFreikerList RealmOwner.display_name)]); with String([qw(Model.ClubPrizeSelectList ->get_prize_credit)]); crédits}],
	['unknown_label' => q{Sélectionner une donnée}],
	['RealmFileVersionsList.selected' => q{Sélectionné}],
	['RealmFileVersionsListForm.selected' => q{Sélectionné}],
	['BulletinForm.ok_button' => q{Envoyer}],
	['ContactForm.ok_button' => q{Envoyer}],
	['CRMForm.ok_button' => q{Envoyer}],
	['MailForm.ok_button' => q{Envoyer}],
	['UserPasswordQueryForm.ok_button' => q{Envoyer}],
	['title.DEFAULT_ERROR_REDIRECT' => q{Erreur - serveur}],
	['ActionError.wiki_name.default' => q{Erreur - serveur}],
	['ActionError.wiki_name.SERVER_ERROR' => q{Erreur - serveur}],
	['HelpWiki.title.USER_SETTINGS_FORM' => q{Paramètres}],
	['task_menu.title.USER_SETTINGS_FORM' => q{Paramètres}],
	['view_rfc822' => q{Montrer l'original}],
	['prose.wiki_view_topic_base' => q{Simple(['Action.WikiView', 'titre']);}],
	['realm_owner_site_admin.GroupUserList.privileges_name.ADMINISTRATOR' => q{Administrateur du site}],
	['realm_owner_site_admin.RoleSelectList.display_name.ADMINISTRATOR' => q{Administrateur du site}],
	['title.SITE_ADMIN_TASK_LOG' => q{Nombre de visites du site}],
	['xlink.task_log' => q{Nombre de visites du site}],
	['realm_owner_site_admin.GroupUserList.privileges_name.ACCOUNTANT' => q{Gérant du site}],
	['realm_owner_site_admin.RoleSelectList.display_name.ACCOUNTANT' => q{Gérant du site}],
	['realm_owner_site_admin.GroupUserList.privileges_name.MEMBER' => q{Employé du site}],
	['realm_owner_site_admin.RoleSelectList.display_name.MEMBER' => q{Employé du site}],
	['RealmFileList.content_length' => q{Taille}],
	['RealmFileTreeList.content_length' => q{Taille}],
	['RealmFolderFileList.content_length' => q{Taille}],
	['prose.MailPartList.attachment' => q{SPAN_label('Pièce-jointe:');SPAN_value(String(['->get_file_name']));}],
	['acknowledgement.paypal_ok' => q{SPAN_money('Merci beaucoup pour votre don!');
Votre transaction a été complétée, et un reçu pour votre achat vous a été envoyé par courriel. Veuillez vous connecter à votre compte XLink('paypal'); pour voir les détails de la transaction.}],
	['task_menu.title.CLUB_FREIKER_LIST_CSV' => q{feuille de calcul}],
	['task_menu.title.FORUM_TUPLE_HISTORY_CSV' => q{feuille de calcul}],
	['task_menu.title.FORUM_TUPLE_LIST_CSV' => q{feuille de calcul}],
	['title.FORUM_CRM_THREAD_ROOT_LIST_CSV' => q{feuille de calcul}],
	['title.GROUP_TASK_LOG_CSV' => q{feuille de calcul}],
	['title.SITE_ADMIN_TASK_LOG_CSV' => q{feuille de calcul}],
	['xlink.FORUM_CRM_THREAD_ROOT_LIST_CSV' => q{feuille de calcul}],
	['TaskLogList.super_user.RealmOwner.name' => q{Employé agissant comme utilisateur}],
	['CalendarEvent.dtstart' => q{début}],
	['dtstart_tz' => q{début}],
	['dtstart_with_tz' => q{début}],
	['Motion.start_date_time' => q{début}],
	['CalendarEventForm.start_date' => q{Date de début}],
	['CalendarEventForm.start_time' => q{Heure de début}],
	['MotionStatus.start_date_time' => q{Heure de début}],
	['state' => q{Province/État}],
	['CRMThreadRootList.CRMThread.crm_thread_status' => q{Statut}],
	['Motion.status' => q{Statut}],
	['Prize.prize_status' => q{Statut}],
	['street1' => q{Adresse ligne 1}],
	['street2' => q{Adresse ligne 2}],
	['prose.EasyForm.update_mail.subject' => q{String(['Action.EasyForm', 'file_path']); soumettre}],
	['xhtml.title.CLUB_FREIKER_RIDE_LIST' => q{String([qw(Model.FreikerRideList ->get_display_name)]); Trajets}],
	['xhtml.title.FAMILY_FREIKER_RIDE_LIST' => q{String([qw(Model.FreikerRideList ->get_display_name)]); Trajets}],
	['title.FORUM_TUPLE_HISTORY' => q{String([qw(Model.TupleUseList TupleUse.label)]); record #String([qw(Model.TupleList Tuple.tuple_num)]); historique}],
	['title.FORUM_TUPLE_LIST' => q{String([qw(Model.TupleUseList TupleUse.label)]); entrées}],
	['CRMThreadRootList.CRMThread.subject' => q{Sujet}],
	['subject' => q{Sujet}],
	['prose.MailHeader.subject' => q{Sujet:}],
	['GroupUserList.privileges_name.MAIL_RECIPIENT' => q{Inscrit}],
	['RoleSelectList.display_name.MAIL_RECIPIENT' => q{Inscrit}],
	['ForumUserList.mail_recipient' => q{Inscrit?}],
	['UserSettingsListForm.is_subscribed' => q{Inscrit?}],
	['UserSubscriptionList.is_subscribed' => q{Inscrit?}],
	['CalendarEventWeekList.Sunday' => q{Dimanche}],
	['ClubFreikerClassList.school_class_display_name' => q{Enseignant}],
	['ClubFreikerList.school_class_display_name' => q{Enseignant}],
	['FreikerList.school_class_display_name' => q{Enseignant}],
	['SchoolClassList.RealmOwner.display_name' => q{Enseignant}],
	['SchoolClassListForm.RealmOwner.display_name' => q{Enseignant}],
	['FreikerImportForm.error.teacher_not_found' => q{Enseignant non trouvé dans la liste des classes}],
	['body' => q{Texte}],
	['prose.UserAuth.create_mail.body' => q{Merci de votre inscription à vs_site_name();.
Afin de compléter votre inscription, veuillez cliquer sur 
le lien suivant:

String(['Model.UserRegisterForm', 'uri']);

Pour votre sécurité, ce lien ne peut être utilisé qu'une seule fois pour programmer votre mot de passe.

Veuillez répondre à ce courriel pour contacter le soutien à la clientèle.

Merci,
vs_site_name(); Support}],
	['acknowledgement.MERCHANT_PRIZE' => q{Merci poru votre don ou votre mise à jour. Veuillez contacter vs_gears_email(); pour discuter de la livraison du prix et la gestion de l'inventaire.}],
	['acknowledgement.FORUM_MOTION_VOTE' => q{Merci d'avoir participer au sondage.}],
	['acknowledgement.FORUM_BLOG_CREATE' => q{Le billet du blogue a été ajouté.}],
	['acknowledgement.FORUM_BLOG_EDIT' => q{La mise à jour du billet du blogue à été sauvegardé.}],
	['acknowledgement.GROUP_BULLETIN_FORM' => q{Le bulletin a été envoyé à String(['Model.BulletinForm', 'to']);.}],
	['acknowledgement.FORUM_CALENDAR_EVENT_FORM.copy' => q{L'évènement a été dupliqué/copié.}],
	['acknowledgement.FORUM_CALENDAR_EVENT_DELETE' => q{L'évènement a été supprimé.}],
	['acknowledgement.FORUM_CALENDAR_EVENT_FORM.edit' => q{L'évènement a été mis à jour.}],
	['acknowledgement.CLUB_FREIKER_ADD' => q{L'enfant a été ajouté}],
	['acknowledgement.FAMILY_FREIKER_ADD' => q{L'enfant a été ajouté}],
	['acknowledgement.CLUB_FREIKER_EDIT' => q{Les renseignements de l'enfant ont été mis à jour.}],
	['acknowledgement.FAMILY_FREIKER_EDIT' => q{Les renseignements sur l'enfant ont été mis à jour.}],
	['acknowledgement.CLUB_MANUAL_RIDE_FORM' => q{La date manquante a été ajoutée.}],
	['acknowledgement.FAMILY_MANUAL_RIDE_FORM' => q{La date manquante a été ajoutée.}],
	['acknowledgement.CLUB_FREIKER_CODE_ADD' => q{Le nouveau code Boltage a été ajouté}],
	['acknowledgement.FAMILY_FREIKER_CODE_ADD' => q{Le nouveau code Boltage a été ajouté}],
	['acknowledgement.FORUM_CALENDAR_EVENT_FORM.create' => q{Le nouvel évènement a été ajouté.}],
	['acknowledgement.GREEN_GEAR_FORM' => q{Le nouveau gagnant hebdomadaire apparaît ci-dessous. Veuillez informer l'enfant qu'il ou qu'elle a gagné.}],
	['form_stale_data_title' => q{Le contenu de la page a été modifié par une autre requête. Veuillez retransmettre le formulaire avec les nouvelles données.}],
	['prose.page_error.model_not_found' => q{La page que vous avez demandé n'a pas été trouvé ou ne fonctionne pas correctement.}],
	['prose.page_error.not_found' => q{La page que vous avez demandé n'a pas été trouvé ou ne fonctionne pas correctement.}],
	['acknowledgement.FORUM_MOTION_FORM' => q{Le sondage a été sauvegardé.}],
	['acknowledgement.FORUM_TUPLE_EDIT' => q{L'entrée a été mise à jour.}],
	['acknowledgement.FORUM_CALENDAR_EVENT_FORM.recurrence' => q{Les évènements récurrents ont été ajoutés.}],
	['acknowledgement.CLUB_PRIZE' => q{Les trajets requis pour le prix ont été mis à jour.}],
	['prose.page_error.server_error' => q{Le serveur éprouve des difficultés en ce moment. Le webmestre en a été informé.}],
	['Image_alt.sort_down' => q{Cette colonne est triée en ordre croissant.}],
	['Image_alt.sort_up' => q{Cette colonne est triée en ordre décroissant.}],
	['ClubRideFillForm.prose.prologue' => q{Ce formulaire est utilisé pour compléter les trajets lorsque le Zap n'était pas en fonction. Les trajets seront ajoutés pour tous les enfants qui ont utilisés leur vélo les deux jours précédents et les deux jours suivant la date que vous avez donné.}],
	['empty_list_prose' => q{Cette liste est vide.}],
	['RemoteCopyList.empty_realm' => q{Ce domaine est à jour.}],
	['RemoteCopyListForm.empty_realm' => q{Ce domaine est à jour.}],
	['CalendarEventWeekList.Thursday' => q{Jeudi}],
	['CRMThreadRootList.CRMThread.crm_thread_num' => q{billet}],
	['feature_crm' => q{billet}],
	['title.FORUM_CRM_THREAD_ROOT_LIST' => q{Billets}],
	['xlink.FORUM_CRM_THREAD_ROOT_LIST' => q{Billets}],
	['time_zone' => q{Fuseau horaire}],
	['time_zone_selector' => q{Fuseau horaire}],
	['BlogCreateForm.title' => q{Titre}],
	['BlogEditForm.title' => q{Titre}],
	['CalendarEventForm.RealmOwner.display_name' => q{Titre}],
	['CalendarEventList.RealmOwner.display_name' => q{Titre}],
	['CalendarEventMonthList.RealmOwner.display_name' => q{Titre}],
	['ForumForm.RealmOwner.display_name' => q{Titre}],
	['ForumList.RealmOwner.display_name' => q{Titre}],
	['WikiForm.RealmFile.path_lc' => q{Titre}],
	['to' => q{À}],
	['SchoolClassList.prose.prologue' => q{Pour ajouter une classe, entrez les renseignements dans un ligne vide. Pour effacer une classe, effacer les données dans la ligne.}],
	['SchoolClassListForm.prose.prologue' => q{Pour ajouter une classe, entrez les renseignements dans un ligne vide. Pour effacer une classe, effacer les données dans la ligne.}],
	['EmailAliasList.EmailAlias.outgoing' => q{Pour envoyer un courriel ou vs_ui_forum();}],
	['MailUnsubscribeForm.prose.prologue' => q{Pour vous enlever des String(['Model.MailUnsubscribeForm', 'realm_display_name']); envois, cliquez sur Désinscrire ci-dessous, ou vous pouvez vous désinscrire de tous les envois à partir de String(vs_site_name());.}],
	['BulletinForm.prose.prologue' => q{Pour envoyer un message test, modifiez seulement la liste À: ci-dessous. Pour publier dans ce communiqué tel quel, cliquez sur envoyer une seule fois.}],
	['prose.MailHeader.to' => q{À:}],
	['MonthList.this_month' => q{Aujourd'hui}],
	['MailForm.subject' => q{sujet}],
	['MailThreadRootList.RealmMail.subject' => q{sujet}],
	['MailThreadRootList.RealmMail.subject_lc' => q{Sujet}],
	['summary_headings.calories' => q{Total des calories brulées}],
	['AdmSummaryBySchoolList.current_kilometers' => q{Total des kilomètres}],
	['ClubFreikerClassList.current_kilometers' => q{Total des kilomètres}],
	['ClubFreikerList.current_kilometers' => q{Total des kilomètres}],
	['ClubSummaryByClassList.current_kilometers' => q{Total des kilomètres}],
	['FreikerList.current_kilometers' => q{Total des kilomètres}],
	['AdmSummaryBySchoolList.current_miles' => q{Total des miles}],
	['ClubFreikerClassList.current_miles' => q{Total des miles}],
	['ClubFreikerList.current_miles' => q{Total des miles}],
	['ClubSummaryByClassList.current_miles' => q{total des miles}],
	['FreikerList.current_miles' => q{Total des miles}],
	['summary_headings.current_miles' => q{Total des miles}],
	['summary_headings.trip_miles' => q{Total des miles}],
	['ClubRegisterForm.club_size.desc' => q{Nombre total d'élèves incluant les enfants et les autres.}],
	['summary_headings.ride_count' => q{total des  trajets}],
	['summary_headings.trips' => q{Total des trajets}],
	['AdmSummaryBySchoolList.display_name_summary_value' => q{Totaux}],
	['ClubSummaryByClassList.display_name_summary_value' => q{totaux}],
	['PrizeRideCount.ride_count' => q{Nombre de trajets}],
	['task_menu.title.CLUB_SUMMARY_BY_SCHOOL_LIST' => q{Sommaire des trajets}],
	['task_menu.title.CLUB_SUMMARY_BY_CLASS_LIST' => q{Sommaire des trajets par classe}],
	['title.CLUB_SUMMARY_BY_CLASS_LIST' => q{Sommaire des trajets par classe}],
	['task_menu.title.ADM_SUMMARY_BY_SCHOOL_LIST' => q{Sommaire des trajets par école}],
	['title.ADM_SUMMARY_BY_SCHOOL_LIST' => q{Sommaire des trajets par école}],
	['CLUB_FREIKER_RIDE_LIST' => q{trajets}],
	['FAMILY_FREIKER_RIDE_LIST' => q{trajets}],
	['ride_count' => q{trajets}],
	['task_menu.title.CLUB_RIDE_DATE_LIST' => q{trajet}],
	['title.CLUB_RIDE_DATE_LIST' => q{Trajets par date}],
	['CalendarEventWeekList.Tuesday' => q{Mardi}],
	['MailUnsubscribeForm.ok_button' => q{Se désinscrire}],
	['title.USER_MAIL_UNSUBSCRIBE_FORM' => q{Se désinscrire}],
	['MailUnsubscribeForm.all_button' => q{Se désinscrire de tous les envois}],
	['ClubFreikerClassListForm.ok_button' => q{Mise à jour}],
	['DBAccessModelForm.update_button' => q{Mise à jour}],
	['UserPasswordForm.ok_button' => q{Mise à jour}],
	['FreikerForm.ok_button' => q{Mettre à jour les renseignements}],
	['xhtml.title.CLUB_FREIKER_EDIT' => q{Mettre à jour les renseignements pour String([qw(Model.FreikerRideList ->get_display_name)]);}],
	['xhtml.title.FAMILY_FREIKER_EDIT' => q{Mettre à jour les renseignements pour String([qw(Model.FreikerRideList ->get_display_name)]);}],
	['task_menu.title.CLUB_FREIKER_CLASS_LIST_FORM' => q{Mettre à jour les classes des enfants}],
	['title.CLUB_FREIKER_CLASS_LIST_FORM' => q{Mettre à jour les classes des enfants}],
	['task_menu.title.CLUB_PRIZE' => q{Mettre à jour les prix}],
	['title.ADM_PRIZE' => q{Mettre à jour les prix}],
	['title.CLUB_PRIZE' => q{Update Prize String(['Model.ClubPrizeList', 'Nom du prix']);}],
	['CRMThreadRootList.modified_by_name' => q{Mis à jour par}],
	['ClubFreikerClassList.new_school_class_id' => q{Classe mise à jour}],
	['ClubFreikerList.new_school_class_id' => q{Classe mise à jour}],
	['FreikerList.new_school_class_id' => q{Classe mise à jour}],
	['TupleHistoryList.slot_headers' => q{Champs mis à jour}],
	['ClubFreikerClassList.new_has_graduated' => q{Diplomé mis à jour}],
	['ClubFreikerList.new_has_graduated' => q{Diplomé mis à jour}],
	['FreikerList.new_has_graduated' => q{Diplomé mis à jour}],
	['title.FORUM_FILE_UPLOAD_FROM_WYSIWYG' => q{télécharger}],
	['FreikerImportForm.error.zip9_invalid' => q{Les Zip Codes doivent contenir 9-chiffres (Zip+4)}],
	['FreikerImportForm.prose.prologue' => q{Utilisez ce formulaire pour inscrire un group d'enfants d'un seul envoi. Link("Cliquez ici pour l'exemple de la feuille de calcul", 'CLUB_FREIKER_IMPORT_EMPTY_CSV');.  Vous aimeriez peut-être Link("réviser la liste des classes de l'école avant de la télécharger", 'CLUB_SCHOOL_CLASS_LIST_FORM');.}],
	['RealmDropDown.user' => q{Utilisateur}],
	['UserSettingsListForm.RealmOwner.name' => q{Identité de l'utilisateur}],
	['UserSubscriptionList.RealmOwner.name' => q{Identité de l'utilisateur}],
	['EmailVerifyForm.ok_button' => q{Vérifier le courriel}],
	['title.USER_EMAIL_VERIFY' => q{Vérifier l'adresse courriel}],
	['CalendarEventMonthForm.b_list_view' => q{Voir les évènements dans une liste}],
	['task_menu.title.FORUM_MOTION_VOTE_LIST_CSV' => q{feuille de calcul des votes}],
	['MotionList.vote_count' => q{Votes [O/N/A]}],
	['prose.UserAuth.password_query_mail.subject' => q{vs_site_name(); Assistance pour le mot de passe}],
	['prose.unapproved_applicant_form_mail_subject' => q{vs_site_name(); Inscription confirmée}],
	['prose.UserAuth.create_mail.subject' => q{vs_site_name(); Vérification de l'inscription}],
	['support_name' => q{vs_site_name(); Soutien}],
	['MerchantInfoForm.prose.prologue' => q{vs_site_name(); fait appel à des marchands locaux comme point de distribution des prix. Vous pouvez également donner et gérer la description des prix sur le site web. Une fois que vous êtes inscrits, nous vous contacterons à propos de la logistique et les frais reliés aux prix.}],
	['prose.UserAuth.general_contact_mail.subject' => q{vs_site_name(); Contact Web}],
	['title.FORUM_CALENDAR_EVENT_FORM' => q{vs_text_as_prose('FORUM_CALENDAR_EVENT_FORM', ['Model.CalendarEventForm', '->form_mode_as_string']); Évènement}],
	['WikiValidator.subject' => q{vs_ui_wiki(); Erreurs}],
	['WikiValidator.title' => q{vs_ui_wiki(); erreurs:}],
	['title.FORUM_WIKI_VERSIONS_LIST' => q{vs_ui_wiki(); Historique de la page}],
	['title.FORUM_WIKI_NOT_FOUND' => q{vs_ui_wiki(); Page introuvable}],
	['ManualRideForm.prose.prologue' => q{Nous permettons un certain nombre de trajets manquants comme courtoisie aux parents.
Lorsqu'il y a trop de trajets manquants, cette liste n'apparaitra plus.
Please enter the date of the missing trip for
String([qw(Model.FreikerRideList ->get_display_name)]);.}],
	['prose.UserAuth.create_done.body' => q{Nous avons envoyé un courriel de confirmation à
String(['Model.UserRegisterForm', 'Email.email']);.
Veuillez suivre les directives se trouvant dans ce courriel afin de compléter votre inscription avec vs_site_name();.}],
	['UserRegisterForm.Email.email.desc' => q{Nous envoyons seulement des courriels concernant vs_site_name();.}],
	['CalendarEventWeekList.Wednesday' => q{Mercredi}],
	['AllClubSummaryList.days_5' => q{semaine}],
	['title.GREEN_GEAR_LIST' => q{Gagnants hebdomadaires}],
	['acknowledgement.password_nak' => q{Nous sommes désolés, mais le "vs_text('xlink.GENERAL_USER_PASSWORD_QUERY');" lien sur lequel vous avez cliqué n'est plus valide. Vous devez réinitialiser votre mot de passe à nouveau.}],
	['xhtml.title.FAMILY_PRIZE_PICKUP' => q{Où aller chercher votre prix!}],
	['RealmFileList.Email_2.email' => q{Qui}],
	['RealmFileList.RealmOwner_2.display_name' => q{Qui}],
	['RealmFileTreeList.Email_2.email' => q{Qui}],
	['RealmFileTreeList.RealmOwner_2.display_name' => q{Qui}],
	['RealmFileVersionsList.Email_2.email' => q{Qui}],
	['RealmFileVersionsList.Email_3.email' => q{Qui}],
	['RealmFileVersionsList.RealmOwner_2.display_name' => q{Qui}],
	['RealmFileVersionsList.RealmOwner_3.display_name' => q{Qui}],
	['RealmFileVersionsListForm.Email_2.email' => q{Qui}],
	['RealmFileVersionsListForm.Email_3.email' => q{Qui}],
	['RealmFileVersionsListForm.RealmOwner_2.display_name' => q{Qui}],
	['RealmFileVersionsListForm.RealmOwner_3.display_name' => q{Qui}],
	['RealmFolderFileList.Email_2.email' => q{Qui}],
	['RealmFolderFileList.RealmOwner_2.display_name' => q{Qui}],
	['TupleHistoryList.RealmMail.from_email' => q{Qui}],
	['acknowledgement.FORUM_WIKI_NOT_FOUND' => q{La page Wiki n'a pas été trouvée. Veuillez la créer.}],
	['prose.CLUB_REGISTER' => q{Aimeriez vous devenir un bénévole? vs_link('Cliquez ici pour inscrire votre école.', 'CLUB_REGISTER');}],
	['birth_year' => q{Année de naissance}],
	['FreikerCodeForm.birth_year' => q{Année de naissance}],
	['FreikerForm.birth_year' => q{Année de naissance}],
	['MotionStatus.yes_count' => q{Oui}],
	['acknowledgement.user_create_password_reset' => q{Vous êtes déjà inscrit. Votre mot de mot a été réinitialisé. Un courriel vous a été envoyé à String([qw(Model.UserPasswordQueryForm Email.email)]); avec un lien qui vous permettra de choisir un nouveau mot de passe.}],
	['prose.page_error.forbidden' => q{Vous n'avez pas l'autorisation pour accéder à cette page.}],
	['UnapprovedApplicantForm.mail_body.default' => q{Vous pouvez accéder à notre site. Si vous avez des questions,
veuillez contact le soutien en répondant à ce message.

Merci,
vs_site_name(); Support}],
	['acknowledgement.user_mail_unsubscribed_all' => q{Vous avez été désincrit de TOUS LES ENVOIS fait par String(vs_site_name());}],
	['acknowledgement.user_mail_unsubscribed' => q{Vous avez été désincrit.}],
	['RemoteCopyList.empty_list_prose' => q{Vous devez créer Settings/RemoteCopy.csv afin de compléter cette opération.}],
	['RemoteCopyListForm.empty_list_prose' => q{Vous devez créer Settings/RemoteCopy.csv afin de compléter cette opération.}],
	['title.DEFAULT_ERROR_REDIRECT_MISSING_COOKIES' => q{Votre navigateur n'accepte pas les fichiers témoin.}],
	['xlink.DEFAULT_ERROR_REDIRECT_MISSING_COOKIES' => q{Votre navigateur n'accepte pas les fichiers témoin.}],
	['acknowledgement.MERCHANT_REGISTER' => q{Votre entreprise est inscrite.}],
	['acknowledgement.paypal_cancel' => q{Votre don a été annulé. Veuillez penser à nous dans le futur.}],
	['ContactForm.from' => q{Votre adresse courriel}],
	['email' => q{Votre adresse courriel}],
	['login' => q{Votre adresse courriel}],
	['acknowledgement.email_verified' => q{Votre adresse courriel a été ajoutée.}],
	['acknowledgement.user_exists' => q{Votre courriel est déjà dans la base de données. Veuillez utiliser le formulaire ci-dessous pour réinitialiser votre mot de passe.}],
	['task_menu.title.back_to_family' => q{Votre famille}],
	['task_menu.title.FAMILY_FREIKER_LIST' => q{Votre famille}],
	['UserRegisterForm.RealmOwner.display_name.desc' => q{Votre prénom et votre nom de famille, pas le nom de votre entreprise ou le nom de l'école.}],
	['display_name' => q{Votre nom complet}],
	['acknowledgement.GENERAL_CONTACT' => q{Votre demande a été envoyée. Merci!}],
	['title.FAMILY_FREIKER_LIST' => q{Vos enfants}],
	['acknowledgement.FORUM_CRM_FORM' => q{Votre message a été envoyé.}],
	['acknowledgement.FORUM_MAIL_FORM' => q{Votre message a été envoyé.}],
	['UserRegisterForm.RealmOwner.display_name' => q{Votre nom}],
	['page3.title.USER_PASSWORD' => q{Votre mot de passe}],
	['xhtml.title.USER_PASSWORD' => q{Votre mot de passe}],
	['acknowledgement.USER_PASSWORD' => q{Votre mot de passe a été modifié.}],
	['acknowledgement.USER_PASSWORD_RESET' => q{Votre mot de passe a été réinitialisé. Veuillez en choisir un nouveau.}],
	['prose.page_error.update_collision' => q{Votre requête ne peut être complétée parce que les données transmises ne sont plus valides.}],
	['acknowledgement.CLUB_REGISTER' => q{Votre école a été enregistrée.}],
	['SearchList.empty_list_prose' => q{Votre recherche correspond à aucun document.}],
	['acknowledgement.USER_SETTINGS_FORM' => q{Vos paramètres ont été mis à jour.}],
	['acknowledgement.USER_FORUM_TREE' => q{Vos abonnements ont été mis à jour.}],
	['freiker_code' => q{étiquette}],
	['freiker_codes' => q{étiquette}],
	['FreikerImportForm.error.freiker_code_already_registered' => q{Cette étiquette est déjà assigné à un enfant}],
	['FreikerImportForm.error.freiker_code_not_found' => q{Ce numéro d'étiquette ne peut être trouvé dans la base de données}],
	['zip' => q{Code postal}],
    ],
});

1;
