#!perl -w
# Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

fr-club - calls Freiker::Util::Club

=head1 SYNOPSIS

fr-club [options] command [args...]

=head1 DESCRIPTION

See L<Freiker::Util::Club|Freiker::Util::Club>

=cut

#=IMPORTS
use Freiker::Util::Club;

#=VARIABLES
Freiker::Util::Club->main(@ARGV);

=head1 SEE ALSO

Freiker::Util::Club

=head1 COPYRIGHT

Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
