#!perl -w
# Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

fr-freikometer - calls Freiker::Util::Freikometer

=head1 SYNOPSIS

fr-freikometer [options] command [args...]

=head1 DESCRIPTION

See L<Freiker::Util::Freikometer|Freiker::Util::Freikometer>

=cut

#=IMPORTS
use Freiker::Util::Freikometer;

#=VARIABLES
Freiker::Util::Freikometer->main(@ARGV);

=head1 SEE ALSO

Freiker::Util::Freikometer

=head1 COPYRIGHT

Copyright (c) 2006 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
