#!perl -w
# Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

fr-green-gear - calls Freiker::Util::GreenGear

=head1 SYNOPSIS

fr-green-gear [options] command [args...]

=head1 DESCRIPTION

See L<Freiker::Util::GreenGear|Freiker::Util::GreenGear>

=cut

#=IMPORTS
use Freiker::Util::GreenGear;

#=VARIABLES
Freiker::Util::GreenGear->main(@ARGV);

=head1 SEE ALSO

Freiker::Util::GreenGear

=head1 COPYRIGHT

Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
