#!perl -w
# Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

fr-prize - calls ShellUtil.Prize

=head1 SYNOPSIS

fr-prize [options] command [args...]

=head1 DESCRIPTION

See ShellUtil. Prize

=cut

#=IMPORTS
use Bivio::ShellUtil;

#=VARIABLES
Bivio::ShellUtil->required_main(Prize => @ARGV);

=head1 SEE ALSO

ShellUtil.Prize

=head1 COPYRIGHT

Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
