#!perl -w
# Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

fr-ride - calls ShellUtil.Ride

=head1 SYNOPSIS

fr-ride [options] command [args...]

=head1 DESCRIPTION

See ShellUtil. Ride

=cut

#=IMPORTS
use Bivio::ShellUtil;

#=VARIABLES
Bivio::ShellUtil->required_main(Ride => @ARGV);

=head1 SEE ALSO

ShellUtil.Ride

=head1 COPYRIGHT

Copyright (c) 2008 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
