#!perl -w
# Copyright (c) 2005 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

fr-sql - calls Freiker::Util::SQL

=head1 RELEASE SCOPE

Freiker

=head1 SYNOPSIS

fr-sql [options] command [args...]

=head1 DESCRIPTION

See L<Freiker::Util::SQL|Freiker::Util::SQL>

=cut

#=IMPORTS
use Freiker::Util::SQL;

#=VARIABLES
Freiker::Util::SQL->main(@ARGV);

=head1 SEE ALSO

Freiker::Util::SQL

=head1 COPYRIGHT

Copyright (c) 2005 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
