#!perl -w
# Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.
# $Id$
use strict;

=head1 NAME

fr-test - calls Freiker::Util::Test

=head1 SYNOPSIS

fr-test [options] command [args...]

=head1 DESCRIPTION

See L<Freiker::Util::Test|Freiker::Util::Test>

=cut

#=IMPORTS
use Freiker::Util::Test;

#=VARIABLES
Freiker::Util::Test->main(@ARGV);

=head1 SEE ALSO

Freiker::Util::Test

=head1 COPYRIGHT

Copyright (c) 2007 bivio Software, Inc.  All Rights Reserved.

=head1 VERSION

$Id$

=cut

#Local Variables:
#mode:cperl
#End:
